### ISSUE TITLE
Make the app responsive for mobile devices, its terrible as of now:')

### ISSUE THREAD

**Issue by sambhavsaxena** [sambhavsaxena/ikigai#1]
The app is not at all responsive, it just works well for desktops/laptops. People who are good with CSS media-queries can be assigned with this issue.

**Comment by VARUN4111** [comment]
I will look at it.

**Comment by sambhavsaxena** [comment]
Sure

**Comment by pardhan007** [comment]
i would like to work on this issue

**Comment by pardhan007** [comment]
PR [7(Harsh Prajapati)](https://github.com/sambhavsaxena/ikigai/pull/7) fixes [#1](https://github.com/sambhavsaxena/ikigai/issues/1).
Review and merge.

**Comment by sambhavsaxena** [comment]
thanks for the contribution
